enter_button = "div.header_flexRow__Xdqv1 > button.buttonSecondary"
popup_no_account_button = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_buttonRow__+W8JD']/button[@type='button']"
registration_form = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_inputColumn__RgD8n']"
registration_email_input = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_inputColumn__RgD8n']//input[@type='text']"
registration_password_input = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_inputColumn__RgD8n']//input[@type='password' and @name='password']"
registration_password_confirm_input = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_inputColumn__RgD8n']//input[@type='password' and @name='submitPassword']"
main_popup_button = "//form[@class='popUp_shell__LuyqR']//div[@class='popUp_buttonRow__+W8JD']/button[@type='submit']"
user_name = "//h3[contains(@class, 'profileText')]"
user_avatar = "//div[@class='header_flexRow__Xdqv1']//button[@class='circleSmall']"
modal = "//div[@class='homePage_modal__zSdUB']"
input_error_wrapper = "//div[@class='input_inputError__fLUP9']"
span_error = "//span[@class='input_span__yWPqB' and text() = 'Ошибка']"
logout_button = "//div[@class='header_flexRow__Xdqv1']//button[text()='Выйти']"
place_ad = "//div[@class='header_flexRow__Xdqv1']//button[text()='Разместить объявление']"
unauth_place_ad_title = "//div[@class='homePage_modal__zSdUB']//div[@class='popUp_titleRow__M7tGg']//h1"
place_ad_title_input = "//form[@class='createListing_shell__A5EA7']//input[@name='name']"
place_ad_description_input = "//form[@class='createListing_shell__A5EA7']//textarea[@name='description']"
place_ad_price_input = "//form[@class='createListing_shell__A5EA7']//input[@name='price']"

place_ad_category_open_button = "//form[@class='createListing_shell__A5EA7']/div[@class='createListing_inputRow__fmwXw']/div[@class='dropDownMenu_dropMenu__sBxhz']/div[@class='dropDownMenu_input__itKtw']/button"
place_ad_category_car_variant = "//form[@class='createListing_shell__A5EA7']/div[@class='createListing_inputRow__fmwXw']/div[@class='dropDownMenu_dropMenu__sBxhz']/div[@class='dropDownMenu_options__CmHmm']/button/span[text()='Авто']"
place_ad_city_open_button = "//form[@class='createListing_shell__A5EA7']/div[@class='dropDownMenu_dropMenu__sBxhz']/div[@class='dropDownMenu_input__itKtw']/button"
place_ad_city_variant = "//form[@class='createListing_shell__A5EA7']/div[@class='dropDownMenu_dropMenu__sBxhz']/div[@class='dropDownMenu_options__CmHmm']/button/span[text()='Новосибирск']"
place_ad_radio = "//input[@name='condition' and @value='Б/У']/../div"
place_ad_submit_button = "//form[@class='createListing_shell__A5EA7']/button[@type='submit']"
my_profile = "//div[@class='header_flexRow__Xdqv1']//button[@class='circleSmall']"
in_profile_ad = "(//div[@class='profilePage_listningBlock__Fi6E5']//div[@class='card']//div[@class='about']/h2)[last()]"
